# permissions for end users to view wanconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wanconfiguration-viewer-role
rules:
- apiGroups:
  - hazelcast.com
  resources:
  - wanconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hazelcast.com
  resources:
  - wanconfigurations/status
  verbs:
  - get
