# permissions for end users to edit wanconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wanconfiguration-editor-role
rules:
- apiGroups:
  - hazelcast.com
  resources:
  - wanconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hazelcast.com
  resources:
  - wanconfigurations/status
  verbs:
  - get
